### ISSUE TITLE
Ingame tracker

### ISSUE THREAD

**Issue by TheNooodle** [TheNooodle/MinishootRandomizer#2]
Use the ingame map to show locations that are available in logic

## Logic parser

- [x] Model (predicates, expression, state)
- [x] Expression parser
- [x] Accessibility check

## UI

- [x] Remove all vanilla markers
- [x] Prototype a way to display markers on the map
- [x] Group locations in interior zones
- [x] Link markers to accessibility of all corresponding locations

## Enhancement ideas (new issues to create)

* Make non accessible locations transparent
* Use dungeon markers to mark completable dungeons

**Comment by TheNooodle** [comment]
Note to self : compare the locations given by the ingame tracker with what the Universal Tracker for Archipelago shows.

**Comment by TheNooodle** [comment]
TODO : make sure that already given items via the plugin are replaced by Super Crystals items, as well as the extra progressive cannon.

**Comment by TheNooodle** [comment]
Done : https://github.com/TheNooodle/MinishootRandomizer/commit/e617aeadb4bb32041c7c93447f4a7e5732dbaf72
